version: "3.4"
networks: #Create network manually if error on creating network due to host restriction e.g. docker create network prometheus
  monitor-net: # "docker network create monitor-net"
    external: true
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - monitor-net
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - AWS_SDK_LOAD_CONFIG=1
      # Grafana image-rendering
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    restart: unless-stopped

  renderer: # https://github.com/grafana/grafana-image-renderer
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'

  snmp_exporter:
    image: prom/snmp-exporter
    networks:
      - monitor-net
    ports:
      - 9116:9116
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/

  prometheus:
    image: prom/prometheus:v2.20.1
    networks:
      - monitor-net
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - monitor-net
    privileged: true
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    ports:
      - '9115:9115'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - monitor-net
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=10s' # https://github.com/google/cadvisor/issues/2523
      - '-docker_only=true' # ^^^^ 19 > ~5%
    depends_on:
    - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
    - monitor-net
    ports:
    - 6379:6379