version: "3.8"
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  grafana:
    image: grafana/grafana:7.1.5
    networks:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - AWS_SDK_LOAD_CONFIG=1
    restart: unless-stopped
  snmp-exporter:
    image: prom/snmp-exporter
    networks:
      - prometheus
    ports:
      - 9116:9116
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
  prometheus:
    image: prom/prometheus:v2.20.1
    networks:
      - prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - prometheus
    privileged: true
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    ports:
      - '9115:9115'
networks:
  prometheus:
    external: true