# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'file_based_sd'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.json
        - /etc/prometheus/device-targets.yml

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

  - job_name: 'snmp_devices'
    static_configs:
      - targets:
        - fw01.onelumen.co.uk
        - ap01.onelumen.co.uk
        - ap02.onelumen.co.uk
        - sw01.onelumen.co.uk
        - sw02.onelumen.co.uk
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:port.

# Blackbox Exporter probes endpoints over HTTP, HTTPS, DNS, TCP or ICMP protocols, returning detailed metrics about the request,
# including whether or not it was successful and how long it took to receive a response.
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://github.com
        - https://google.com
        - http://hassio.onelumen.co.uk:8123/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115 #inside dockercompose

  - job_name: blackbox-ping
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 9.9.9.9   # <== Put here your targets
        - fw01.onelumen.co.uk
        - ap01.onelumen.co.uk
        - ap02.onelumen.co.uk
        - sw01.onelumen.co.uk
        - sw02.onelumen.co.uk
        - 176.97.155.137
        - hassio.onelumen.co.uk
          # <== Put here your targets
    relabel_configs:    # <== This comes from the blackbox exporter README
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115 # Blackbox exporter.

  - job_name: "hass"
    scrape_interval: 60s
    metrics_path: /api/prometheus
    # Long-Lived Access Token
    authorization:
      credentials: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIwOTdmOGNkNzI5NzU0N2QwYjkyMzY1Y2UwNGU0YTUxZiIsImlhdCI6MTYyODg5NTIwMiwiZXhwIjoxOTQ0MjU1MjAyfQ.1JXm4f624Z0qwcZAa6CM2SX13tA-k6JlICT8paeypSk"

    scheme: http
    static_configs:
      - targets: ['192.168.0.201:8123']

  - job_name: "speedtest"
    scrape_interval: 1h
    scrape_timeout: 1m
    # static_configs:
    #   - targets: ['speedtest-exporter:9798']
    file_sd_configs:
      - files:
        - /etc/prometheus/speedtest.yml
