global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'homeassistant'
    scrape_interval: 30s
    metrics_path: /api/prometheus
    authorization:
      credentials: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhYTliMGM2Mjk0ZTc0NDQ2ODg0Y2RiNjU4ZTIxYjNjZiIsImlhdCI6MTc3MjEyMzg2OSwiZXhwIjoyMDg3NDgzODY5fQ.6H4fXpSY1gEFWDPUDkE3q6FegjbpimIRgmXPipAlmCk
    static_configs:
      - targets: ['192.168.0.201:8123']

  - job_name: 'node-exporter-pi'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.0.30:9100']

  - job_name: 'node-exporter-macmini'
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.0.50:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mac-mini'

  - job_name: 'node-exporter-sp3'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.0.170:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'sp3'

  - job_name: 'traefik'
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.0.55:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'traefik-nas'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx_no_tls]
    static_configs:
      - targets:
        - https://obsidian.onelumen.co.uk
        - https://grafana.onelumen.co.uk
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: 'snmp_fw01'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.0.254']
    metrics_path: /snmp
    params:
      module: [if_mib]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116

  - job_name: 'snmp_fw01_system'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.0.254']
    metrics_path: /snmp
    params:
      module: [edgerouter]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116

  - job_name: 'cadvisor_nas'
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.0.185:8090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nas'
