auths:
  public_v2:
    community: public
    version: 2
modules:
  if_mib:
    walk:
      - 1.3.6.1.2.1.2
      - 1.3.6.1.2.1.31.1.1
    get:
      - 1.3.6.1.2.1.1.3.0
    metrics:
      - name: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: DisplayString
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifHCInOctets
        oid: 1.3.6.1.2.1.31.1.1.1.6
        type: counter
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifHCOutOctets
        oid: 1.3.6.1.2.1.31.1.1.1.10
        type: counter
        indexes:
          - labelname: ifIndex
            type: gauge
  edgerouter:
    get:
      - 1.3.6.1.2.1.1.3.0
      - 1.3.6.1.4.1.2021.4.5.0
      - 1.3.6.1.4.1.2021.4.6.0
      - 1.3.6.1.4.1.2021.4.15.0
    walk:
      - 1.3.6.1.4.1.2021.10.1.3
    metrics:
      - name: sysUpTime
        oid: 1.3.6.1.2.1.1.3.0
        type: gauge
      - name: memTotalReal
        oid: 1.3.6.1.4.1.2021.4.5.0
        type: gauge
      - name: memAvailReal
        oid: 1.3.6.1.4.1.2021.4.6.0
        type: gauge
      - name: memBuffer
        oid: 1.3.6.1.4.1.2021.4.15.0
        type: gauge
      - name: laLoad
        oid: 1.3.6.1.4.1.2021.10.1.3
        type: DisplayString
        indexes:
          - labelname: laIndex
            type: gauge
