apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://192.168.0.185:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceID":"(\w+)"'
          name: TraceID
          url: '${__value.raw}'
    version: 1
    editable: true

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://192.168.0.185:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags: [{ key: 'service.name', value: 'service' }]
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }]
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    version: 1
    editable: true
